use_frameworks!

target 'KProgressHUD_Example' do
  platform :ios, '10.0'
  pod 'KProgressHUD', :path => '../'

  target 'KProgressHUD_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
